### ISSUE TITLE
Five broken tests (June 2024)

### ISSUE THREAD

**Issue by KirkLandTrip** [mandiant/macos-UnifiedLogs#17]
Hey
I tried building & running tests today. I used the last tests.zip from the release "Milestone 1" which is from August 2022.
There are currently 5 failed tests:
```
failures:

---- parser::tests::test_collect_shared_strings_system stdout ----
thread 'parser::tests::test_collect_shared_strings_system' panicked at src\parser.rs:397:70:
called `Result::unwrap()` on an `Err` value: Path

---- parser::tests::test_collect_strings_system stdout ----
thread 'parser::tests::test_collect_strings_system' panicked at src\parser.rs:363:57:
called `Result::unwrap()` on an `Err` value: Dir

---- parser::tests::test_collect_timesync_system stdout ----
thread 'parser::tests::test_collect_timesync_system' panicked at src\parser.rs:369:58:
called `Result::unwrap()` on an `Err` value: Path

---- parser::tests::test_collect_strings_archive stdout ----
thread 'parser::tests::test_collect_strings_archive' panicked at src\parser.rs:431:9:
assertion `left == right` failed
  left: "B6B65F4DC53ED38FEB0DDF61809853"
 right: "5283D7FC2531558F2C1ACE9AF26A0F"

---- parser::tests::test_shared_strings_archive stdout ----
thread 'parser::tests::test_shared_strings_archive' panicked at src\parser.rs:411:9:
assertion `left == right` failed
  left: 532
 right: 1976


failures:
    parser::tests::test_collect_shared_strings_system
    parser::tests::test_collect_strings_archive
    parser::tests::test_collect_strings_system
    parser::tests::test_collect_timesync_system
    parser::tests::test_shared_strings_archive

test result: FAILED. 186 passed; 5 failed; 0 ignored; 0 measured; 0 filtered out; finished in 13.72s
```

I'm guessing fixes to the code broke the tests over time. Do you guys have updated versions of those tests that you can release?
Thank you.

**Comment by puffyCid** [comment]
As mentioned in [BUILDING.md](https://github.com/mandiant/macos-UnifiedLogs/blob/main/BUILDING.md).

Please make sure to download the tests.zip file from the release link and extract to your local repo if you want to run tests.

Let me know if u still get errors after running the tests

**Comment by KirkLandTrip** [comment]
That's exactly what I did.  
Other tests also use files from `tests.zip` and they passed.  
It's just those 5 that even with the extracted files don't pass.

**Comment by puffyCid** [comment]
Are you on a macOS laptop?
Unfortunately, some of these test expect a macOS system.  The tests below require macOS, sorry.
```
---- parser::tests::test_collect_shared_strings_system stdout ----
thread 'parser::tests::test_collect_shared_strings_system' panicked at src\parser.rs:397:70:
called `Result::unwrap()` on an `Err` value: Path

---- parser::tests::test_collect_strings_system stdout ----
thread 'parser::tests::test_collect_strings_system' panicked at src\parser.rs:363:57:
called `Result::unwrap()` on an `Err` value: Dir

---- parser::tests::test_collect_timesync_system stdout ----
thread 'parser::tests::test_collect_timesync_system' panicked at src\parser.rs:369:58:
called `Result::unwrap()` on an `Err` value: Path
```

The 2 other tests should not require macOS. I downloaded the lastest code from the repo and the test.zip file.  Both tests ran fine. Did you try redownloading the tests.zip file? Perhaps, a file was removed by mistake?

**Comment by puffyCid** [comment]
this should be fixed now
